name: deploy-thiagoresende.dev
on:
  push:
    branches:
      - main
jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
      - run: yarn
  type-check:
    needs: install
    runs-on: ubuntu-latest
    steps:
      - run: yarn type-check
      - run: yarn test
  test:
    needs: type-check
    runs-on: ubuntu-latest
    steps:
      - run: yarn test
