name: deploy-thiagoresende.dev
on:
  push:
    branches:
      - main
jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
      - run: yarn
      - uses: actions/upload-artifact@master
        with:
          name: install
          path: .      
  type-check:
    needs: install
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@master
        with:
          name: install
          path: .
      - run: yarn type-check
      - run: yarn test
  test:
    needs: install
    runs-on: ubuntu-latest
    steps:
      - run: yarn test
